apiVersion: v1
kind: Pod
metadata:
  namespace: ns-ecr-renew-demo
  name: ecr-image-pull-test-demo
  labels:
    name: ecr-image-pull-test-demo
spec:
  imagePullSecrets:
    - name: ecr-docker-login-demo
  containers:
    - name: my-test-container-demo
      image: [ECR_URI]
      ports:
        - containerPort: 80
          